// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: codenet/codenet/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetEncodedDataByIdRequest struct {
	EncodedDataId uint64 `protobuf:"varint,1,opt,name=encodedDataId,proto3" json:"encodedDataId,omitempty"`
}

func (m *QueryGetEncodedDataByIdRequest) Reset()         { *m = QueryGetEncodedDataByIdRequest{} }
func (m *QueryGetEncodedDataByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetEncodedDataByIdRequest) ProtoMessage()    {}
func (*QueryGetEncodedDataByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{2}
}
func (m *QueryGetEncodedDataByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEncodedDataByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEncodedDataByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEncodedDataByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEncodedDataByIdRequest.Merge(m, src)
}
func (m *QueryGetEncodedDataByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEncodedDataByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEncodedDataByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEncodedDataByIdRequest proto.InternalMessageInfo

func (m *QueryGetEncodedDataByIdRequest) GetEncodedDataId() uint64 {
	if m != nil {
		return m.EncodedDataId
	}
	return 0
}

type QueryGetEncodedDataByIdResponse struct {
	EncodedData *EncodedData `protobuf:"bytes,1,opt,name=encodedData,proto3" json:"encodedData,omitempty"`
}

func (m *QueryGetEncodedDataByIdResponse) Reset()         { *m = QueryGetEncodedDataByIdResponse{} }
func (m *QueryGetEncodedDataByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetEncodedDataByIdResponse) ProtoMessage()    {}
func (*QueryGetEncodedDataByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{3}
}
func (m *QueryGetEncodedDataByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEncodedDataByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEncodedDataByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEncodedDataByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEncodedDataByIdResponse.Merge(m, src)
}
func (m *QueryGetEncodedDataByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEncodedDataByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEncodedDataByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEncodedDataByIdResponse proto.InternalMessageInfo

func (m *QueryGetEncodedDataByIdResponse) GetEncodedData() *EncodedData {
	if m != nil {
		return m.EncodedData
	}
	return nil
}

type QueryGetProofByIdRequest struct {
	EncodedDataId uint64 `protobuf:"varint,1,opt,name=encodedDataId,proto3" json:"encodedDataId,omitempty"`
}

func (m *QueryGetProofByIdRequest) Reset()         { *m = QueryGetProofByIdRequest{} }
func (m *QueryGetProofByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetProofByIdRequest) ProtoMessage()    {}
func (*QueryGetProofByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{4}
}
func (m *QueryGetProofByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProofByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProofByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProofByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProofByIdRequest.Merge(m, src)
}
func (m *QueryGetProofByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProofByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProofByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProofByIdRequest proto.InternalMessageInfo

func (m *QueryGetProofByIdRequest) GetEncodedDataId() uint64 {
	if m != nil {
		return m.EncodedDataId
	}
	return 0
}

type QueryGetProofByIdResponse struct {
	Proof []uint64 `protobuf:"varint,1,rep,packed,name=proof,proto3" json:"proof,omitempty"`
}

func (m *QueryGetProofByIdResponse) Reset()         { *m = QueryGetProofByIdResponse{} }
func (m *QueryGetProofByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetProofByIdResponse) ProtoMessage()    {}
func (*QueryGetProofByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{5}
}
func (m *QueryGetProofByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProofByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProofByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProofByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProofByIdResponse.Merge(m, src)
}
func (m *QueryGetProofByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProofByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProofByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProofByIdResponse proto.InternalMessageInfo

func (m *QueryGetProofByIdResponse) GetProof() []uint64 {
	if m != nil {
		return m.Proof
	}
	return nil
}

type QueryGetCreatorByIdRequest struct {
	EncodedDataId uint64 `protobuf:"varint,1,opt,name=encodedDataId,proto3" json:"encodedDataId,omitempty"`
}

func (m *QueryGetCreatorByIdRequest) Reset()         { *m = QueryGetCreatorByIdRequest{} }
func (m *QueryGetCreatorByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatorByIdRequest) ProtoMessage()    {}
func (*QueryGetCreatorByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{6}
}
func (m *QueryGetCreatorByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatorByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatorByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatorByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatorByIdRequest.Merge(m, src)
}
func (m *QueryGetCreatorByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatorByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatorByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatorByIdRequest proto.InternalMessageInfo

func (m *QueryGetCreatorByIdRequest) GetEncodedDataId() uint64 {
	if m != nil {
		return m.EncodedDataId
	}
	return 0
}

type QueryGetCreatorByIdResponse struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *QueryGetCreatorByIdResponse) Reset()         { *m = QueryGetCreatorByIdResponse{} }
func (m *QueryGetCreatorByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatorByIdResponse) ProtoMessage()    {}
func (*QueryGetCreatorByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{7}
}
func (m *QueryGetCreatorByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatorByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatorByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatorByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatorByIdResponse.Merge(m, src)
}
func (m *QueryGetCreatorByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatorByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatorByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatorByIdResponse proto.InternalMessageInfo

func (m *QueryGetCreatorByIdResponse) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type QueryGetVerificationStatusByIdRequest struct {
	EncodedDataId uint64 `protobuf:"varint,1,opt,name=encodedDataId,proto3" json:"encodedDataId,omitempty"`
}

func (m *QueryGetVerificationStatusByIdRequest) Reset()         { *m = QueryGetVerificationStatusByIdRequest{} }
func (m *QueryGetVerificationStatusByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVerificationStatusByIdRequest) ProtoMessage()    {}
func (*QueryGetVerificationStatusByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{8}
}
func (m *QueryGetVerificationStatusByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVerificationStatusByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVerificationStatusByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVerificationStatusByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVerificationStatusByIdRequest.Merge(m, src)
}
func (m *QueryGetVerificationStatusByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVerificationStatusByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVerificationStatusByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVerificationStatusByIdRequest proto.InternalMessageInfo

func (m *QueryGetVerificationStatusByIdRequest) GetEncodedDataId() uint64 {
	if m != nil {
		return m.EncodedDataId
	}
	return 0
}

type QueryGetVerificationStatusByIdResponse struct {
	VerificationStatus string `protobuf:"bytes,1,opt,name=verificationStatus,proto3" json:"verificationStatus,omitempty"`
}

func (m *QueryGetVerificationStatusByIdResponse) Reset() {
	*m = QueryGetVerificationStatusByIdResponse{}
}
func (m *QueryGetVerificationStatusByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVerificationStatusByIdResponse) ProtoMessage()    {}
func (*QueryGetVerificationStatusByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd912081da53b2a6, []int{9}
}
func (m *QueryGetVerificationStatusByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVerificationStatusByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVerificationStatusByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVerificationStatusByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVerificationStatusByIdResponse.Merge(m, src)
}
func (m *QueryGetVerificationStatusByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVerificationStatusByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVerificationStatusByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVerificationStatusByIdResponse proto.InternalMessageInfo

func (m *QueryGetVerificationStatusByIdResponse) GetVerificationStatus() string {
	if m != nil {
		return m.VerificationStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "codenet.codenet.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "codenet.codenet.QueryParamsResponse")
	proto.RegisterType((*QueryGetEncodedDataByIdRequest)(nil), "codenet.codenet.QueryGetEncodedDataByIdRequest")
	proto.RegisterType((*QueryGetEncodedDataByIdResponse)(nil), "codenet.codenet.QueryGetEncodedDataByIdResponse")
	proto.RegisterType((*QueryGetProofByIdRequest)(nil), "codenet.codenet.QueryGetProofByIdRequest")
	proto.RegisterType((*QueryGetProofByIdResponse)(nil), "codenet.codenet.QueryGetProofByIdResponse")
	proto.RegisterType((*QueryGetCreatorByIdRequest)(nil), "codenet.codenet.QueryGetCreatorByIdRequest")
	proto.RegisterType((*QueryGetCreatorByIdResponse)(nil), "codenet.codenet.QueryGetCreatorByIdResponse")
	proto.RegisterType((*QueryGetVerificationStatusByIdRequest)(nil), "codenet.codenet.QueryGetVerificationStatusByIdRequest")
	proto.RegisterType((*QueryGetVerificationStatusByIdResponse)(nil), "codenet.codenet.QueryGetVerificationStatusByIdResponse")
}

func init() { proto.RegisterFile("codenet/codenet/query.proto", fileDescriptor_fd912081da53b2a6) }

var fileDescriptor_fd912081da53b2a6 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0xda, 0x46, 0xfa, 0xea, 0x0f, 0x1c, 0x0b, 0x4d, 0xb6, 0x65, 0x53, 0xd6, 0x2a,
	0x35, 0x4a, 0xa6, 0x89, 0x62, 0xb4, 0x87, 0x5a, 0xa2, 0x56, 0x7a, 0x10, 0xda, 0x15, 0x44, 0xbc,
	0x84, 0x49, 0x76, 0xba, 0x2c, 0x98, 0x9d, 0xed, 0xee, 0xa4, 0x18, 0xc4, 0x8b, 0x7f, 0x81, 0xe0,
	0x1f, 0xe0, 0x51, 0x8f, 0x1e, 0xfd, 0x13, 0x7a, 0x2c, 0xe8, 0x41, 0x10, 0x44, 0x12, 0xc1, 0x7f,
	0x43, 0x32, 0x3b, 0xab, 0x9b, 0xec, 0x6e, 0x4d, 0x2e, 0xd9, 0xd9, 0x37, 0xef, 0xfb, 0x7d, 0x9f,
	0xc9, 0xbc, 0xc7, 0xc2, 0x52, 0x9b, 0x5b, 0xcc, 0x65, 0x82, 0x44, 0xcf, 0x83, 0x2e, 0xf3, 0x7b,
	0x15, 0xcf, 0xe7, 0x82, 0xe3, 0x0b, 0x2a, 0x58, 0x51, 0x4f, 0xed, 0x22, 0xed, 0x38, 0x2e, 0x27,
	0xf2, 0x37, 0xcc, 0xd1, 0x16, 0x6c, 0x6e, 0x73, 0xb9, 0x24, 0xc3, 0x95, 0x8a, 0x2e, 0xdb, 0x9c,
	0xdb, 0x2f, 0x18, 0xa1, 0x9e, 0x43, 0xa8, 0xeb, 0x72, 0x41, 0x85, 0xc3, 0xdd, 0x40, 0xed, 0x96,
	0xdb, 0x3c, 0xe8, 0xf0, 0x80, 0xb4, 0x68, 0xc0, 0xc2, 0x82, 0xe4, 0xb0, 0xda, 0x62, 0x82, 0x56,
	0x89, 0x47, 0x6d, 0xc7, 0x95, 0xc9, 0x91, 0xd3, 0x38, 0xa0, 0x47, 0x7d, 0xda, 0x89, 0x9c, 0x8c,
	0xf1, 0x5d, 0xe6, 0x0e, 0x57, 0x56, 0xd3, 0xa2, 0x82, 0x86, 0x39, 0xc6, 0x02, 0xe0, 0xbd, 0x61,
	0x8d, 0x5d, 0x29, 0x34, 0xd9, 0x41, 0x97, 0x05, 0xc2, 0xd8, 0x83, 0x4b, 0x23, 0xd1, 0xc0, 0xe3,
	0x6e, 0xc0, 0xf0, 0x06, 0xe4, 0xc3, 0x02, 0x05, 0xb4, 0x82, 0xd6, 0xe6, 0x6b, 0x8b, 0x95, 0xb1,
	0xff, 0xa0, 0x12, 0x0a, 0x1a, 0x73, 0x47, 0x3f, 0x4a, 0xb9, 0x8f, 0xbf, 0x3f, 0x95, 0x91, 0xa9,
	0x14, 0xc6, 0x36, 0xe8, 0xd2, 0xf2, 0x11, 0x13, 0x0f, 0x43, 0x8c, 0x07, 0x54, 0xd0, 0x46, 0x6f,
	0xc7, 0x52, 0x45, 0xf1, 0x2a, 0x9c, 0x63, 0xff, 0x76, 0x76, 0x2c, 0x59, 0x64, 0xc6, 0x1c, 0x0d,
	0x1a, 0x14, 0x4a, 0x99, 0x3e, 0x0a, 0x73, 0x13, 0xe6, 0x63, 0x1a, 0xc5, 0xba, 0x9c, 0x60, 0x8d,
	0xc9, 0xcd, 0xb8, 0xc0, 0xd8, 0x82, 0x42, 0x54, 0x62, 0xd7, 0xe7, 0x7c, 0x7f, 0x7a, 0xc8, 0x2a,
	0x14, 0x53, 0x1c, 0x14, 0xde, 0x02, 0xcc, 0x7a, 0xc3, 0x60, 0x01, 0xad, 0x9c, 0x5e, 0x9b, 0x31,
	0xc3, 0x17, 0xa3, 0x01, 0x5a, 0x24, 0xb9, 0xef, 0x33, 0x2a, 0xb8, 0x3f, 0x7d, 0xd9, 0x3a, 0x2c,
	0xa5, 0x7a, 0xa8, 0xc2, 0x05, 0x38, 0xd3, 0x0e, 0xc3, 0x52, 0x3e, 0x67, 0x46, 0xaf, 0xc6, 0x63,
	0xb8, 0x12, 0x09, 0x9f, 0x32, 0xdf, 0xd9, 0x77, 0xda, 0xb2, 0xcb, 0x9e, 0x08, 0x2a, 0xba, 0xc1,
	0xf4, 0x1c, 0xcf, 0xe0, 0xea, 0xff, 0xec, 0x14, 0x52, 0x05, 0xf0, 0x61, 0x22, 0x43, 0xd1, 0xa5,
	0xec, 0xd4, 0xbe, 0xe7, 0x61, 0x56, 0x5a, 0x63, 0x01, 0xf9, 0xb0, 0xd9, 0xf0, 0xe5, 0xc4, 0xcd,
	0x26, 0x3b, 0x5a, 0x5b, 0x3d, 0x39, 0x29, 0xc4, 0x31, 0x4a, 0x6f, 0xbe, 0xfc, 0x7a, 0x77, 0xaa,
	0x88, 0x17, 0x49, 0xfa, 0x60, 0xe1, 0xcf, 0x08, 0x70, 0xb2, 0xf3, 0x30, 0x49, 0x77, 0xcf, 0xec,
	0x75, 0x6d, 0x7d, 0x72, 0x81, 0x42, 0xbb, 0x27, 0xd1, 0xee, 0xe2, 0x7a, 0x02, 0xcd, 0x66, 0xa2,
	0x19, 0x9f, 0xec, 0x66, 0xab, 0xd7, 0x74, 0x2c, 0xf2, 0x6a, 0xe4, 0x4e, 0x5e, 0xe3, 0xf7, 0x08,
	0xce, 0xc6, 0xfb, 0x11, 0x5f, 0xcb, 0x64, 0x18, 0xef, 0x7a, 0xad, 0x3c, 0x49, 0xaa, 0x02, 0xbd,
	0x23, 0x41, 0x6b, 0x78, 0x3d, 0x15, 0x54, 0x36, 0x7b, 0x06, 0xe1, 0x07, 0x04, 0xe7, 0x47, 0x5b,
	0x17, 0x5f, 0xcf, 0x2c, 0x9c, 0x1c, 0x12, 0xed, 0xc6, 0x64, 0xc9, 0x8a, 0x73, 0x43, 0x72, 0xde,
	0xc2, 0xb5, 0x54, 0x4e, 0x35, 0x19, 0x19, 0xa4, 0x5f, 0x11, 0x14, 0x33, 0x9b, 0x1b, 0xdf, 0xce,
	0xe4, 0x38, 0x71, 0xb8, 0xb4, 0xfa, 0xd4, 0x3a, 0x75, 0x94, 0x6d, 0x79, 0x94, 0x2d, 0xbc, 0x99,
	0x7a, 0x94, 0xf8, 0x18, 0x35, 0x03, 0xa9, 0x4e, 0x3f, 0x56, 0xa3, 0x7a, 0xd4, 0xd7, 0xd1, 0x71,
	0x5f, 0x47, 0x3f, 0xfb, 0x3a, 0x7a, 0x3b, 0xd0, 0x73, 0xc7, 0x03, 0x3d, 0xf7, 0x6d, 0xa0, 0xe7,
	0x9e, 0x2f, 0x46, 0x86, 0x2f, 0xff, 0x5a, 0x8b, 0x9e, 0xc7, 0x82, 0x56, 0x5e, 0x7e, 0x46, 0x6e,
	0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x81, 0x43, 0xff, 0x3c, 0x2b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetEncodedDataById items.
	GetEncodedDataById(ctx context.Context, in *QueryGetEncodedDataByIdRequest, opts ...grpc.CallOption) (*QueryGetEncodedDataByIdResponse, error)
	// Queries a list of GetProofById items.
	GetProofById(ctx context.Context, in *QueryGetProofByIdRequest, opts ...grpc.CallOption) (*QueryGetProofByIdResponse, error)
	// Queries a list of GetCreatorById items.
	GetCreatorById(ctx context.Context, in *QueryGetCreatorByIdRequest, opts ...grpc.CallOption) (*QueryGetCreatorByIdResponse, error)
	// Queries a list of GetVerificationStatusById items.
	GetVerificationStatusById(ctx context.Context, in *QueryGetVerificationStatusByIdRequest, opts ...grpc.CallOption) (*QueryGetVerificationStatusByIdResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/codenet.codenet.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetEncodedDataById(ctx context.Context, in *QueryGetEncodedDataByIdRequest, opts ...grpc.CallOption) (*QueryGetEncodedDataByIdResponse, error) {
	out := new(QueryGetEncodedDataByIdResponse)
	err := c.cc.Invoke(ctx, "/codenet.codenet.Query/GetEncodedDataById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProofById(ctx context.Context, in *QueryGetProofByIdRequest, opts ...grpc.CallOption) (*QueryGetProofByIdResponse, error) {
	out := new(QueryGetProofByIdResponse)
	err := c.cc.Invoke(ctx, "/codenet.codenet.Query/GetProofById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCreatorById(ctx context.Context, in *QueryGetCreatorByIdRequest, opts ...grpc.CallOption) (*QueryGetCreatorByIdResponse, error) {
	out := new(QueryGetCreatorByIdResponse)
	err := c.cc.Invoke(ctx, "/codenet.codenet.Query/GetCreatorById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetVerificationStatusById(ctx context.Context, in *QueryGetVerificationStatusByIdRequest, opts ...grpc.CallOption) (*QueryGetVerificationStatusByIdResponse, error) {
	out := new(QueryGetVerificationStatusByIdResponse)
	err := c.cc.Invoke(ctx, "/codenet.codenet.Query/GetVerificationStatusById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetEncodedDataById items.
	GetEncodedDataById(context.Context, *QueryGetEncodedDataByIdRequest) (*QueryGetEncodedDataByIdResponse, error)
	// Queries a list of GetProofById items.
	GetProofById(context.Context, *QueryGetProofByIdRequest) (*QueryGetProofByIdResponse, error)
	// Queries a list of GetCreatorById items.
	GetCreatorById(context.Context, *QueryGetCreatorByIdRequest) (*QueryGetCreatorByIdResponse, error)
	// Queries a list of GetVerificationStatusById items.
	GetVerificationStatusById(context.Context, *QueryGetVerificationStatusByIdRequest) (*QueryGetVerificationStatusByIdResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetEncodedDataById(ctx context.Context, req *QueryGetEncodedDataByIdRequest) (*QueryGetEncodedDataByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEncodedDataById not implemented")
}
func (*UnimplementedQueryServer) GetProofById(ctx context.Context, req *QueryGetProofByIdRequest) (*QueryGetProofByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProofById not implemented")
}
func (*UnimplementedQueryServer) GetCreatorById(ctx context.Context, req *QueryGetCreatorByIdRequest) (*QueryGetCreatorByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreatorById not implemented")
}
func (*UnimplementedQueryServer) GetVerificationStatusById(ctx context.Context, req *QueryGetVerificationStatusByIdRequest) (*QueryGetVerificationStatusByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerificationStatusById not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codenet.codenet.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetEncodedDataById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEncodedDataByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEncodedDataById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codenet.codenet.Query/GetEncodedDataById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEncodedDataById(ctx, req.(*QueryGetEncodedDataByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProofById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProofByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProofById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codenet.codenet.Query/GetProofById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProofById(ctx, req.(*QueryGetProofByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCreatorById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCreatorByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCreatorById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codenet.codenet.Query/GetCreatorById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCreatorById(ctx, req.(*QueryGetCreatorByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetVerificationStatusById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVerificationStatusByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVerificationStatusById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codenet.codenet.Query/GetVerificationStatusById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVerificationStatusById(ctx, req.(*QueryGetVerificationStatusByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "codenet.codenet.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetEncodedDataById",
			Handler:    _Query_GetEncodedDataById_Handler,
		},
		{
			MethodName: "GetProofById",
			Handler:    _Query_GetProofById_Handler,
		},
		{
			MethodName: "GetCreatorById",
			Handler:    _Query_GetCreatorById_Handler,
		},
		{
			MethodName: "GetVerificationStatusById",
			Handler:    _Query_GetVerificationStatusById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codenet/codenet/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetEncodedDataByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEncodedDataByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEncodedDataByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EncodedDataId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEncodedDataByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEncodedDataByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEncodedDataByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EncodedData != nil {
		{
			size, err := m.EncodedData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetProofByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProofByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProofByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EncodedDataId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetProofByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProofByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProofByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		dAtA4 := make([]byte, len(m.Proof)*10)
		var j3 int
		for _, num := range m.Proof {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintQuery(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatorByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatorByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatorByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EncodedDataId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatorByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatorByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatorByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVerificationStatusByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVerificationStatusByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVerificationStatusByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EncodedDataId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVerificationStatusByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVerificationStatusByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVerificationStatusByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerificationStatus) > 0 {
		i -= len(m.VerificationStatus)
		copy(dAtA[i:], m.VerificationStatus)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VerificationStatus)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetEncodedDataByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		n += 1 + sovQuery(uint64(m.EncodedDataId))
	}
	return n
}

func (m *QueryGetEncodedDataByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EncodedData != nil {
		l = m.EncodedData.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetProofByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		n += 1 + sovQuery(uint64(m.EncodedDataId))
	}
	return n
}

func (m *QueryGetProofByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Proof) > 0 {
		l = 0
		for _, e := range m.Proof {
			l += sovQuery(uint64(e))
		}
		n += 1 + sovQuery(uint64(l)) + l
	}
	return n
}

func (m *QueryGetCreatorByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		n += 1 + sovQuery(uint64(m.EncodedDataId))
	}
	return n
}

func (m *QueryGetCreatorByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVerificationStatusByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EncodedDataId != 0 {
		n += 1 + sovQuery(uint64(m.EncodedDataId))
	}
	return n
}

func (m *QueryGetVerificationStatusByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VerificationStatus)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEncodedDataByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEncodedDataByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEncodedDataByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodedDataId", wireType)
			}
			m.EncodedDataId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncodedDataId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEncodedDataByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEncodedDataByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEncodedDataByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodedData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EncodedData == nil {
				m.EncodedData = &EncodedData{}
			}
			if err := m.EncodedData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProofByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProofByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProofByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodedDataId", wireType)
			}
			m.EncodedDataId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncodedDataId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProofByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProofByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProofByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Proof = append(m.Proof, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthQuery
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthQuery
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Proof) == 0 {
					m.Proof = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Proof = append(m.Proof, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatorByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatorByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatorByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodedDataId", wireType)
			}
			m.EncodedDataId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncodedDataId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatorByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatorByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatorByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVerificationStatusByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVerificationStatusByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVerificationStatusByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodedDataId", wireType)
			}
			m.EncodedDataId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncodedDataId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVerificationStatusByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVerificationStatusByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVerificationStatusByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
